### ISSUE TITLE
Add Algorithms in Java

### ISSUE THREAD

**Issue by darpanjbora** [darpanjbora/Java-Algorithms#1]
### Follow these steps to make your first pull request - 

1. Fork this repo.
2. Clone your forked repository to your local.
3. Add any Algorithm **(JAVA ONLY)** in its respective folder. (You can create a folder, if it's not there)
4. Then create a pull request.

**Comment by Pika1998** [comment]
I'd like to work on this

**Comment by kushverma86** [comment]
Added backtracking solution to N-Queens and FindPath

**Comment by kushverma86** [comment]
Added coin change, Hamiltonian Path and Subset Sums

**Comment by yukta12** [comment]
Operating system algorithms are missing 
Can i add one?

**Comment by darpanjbora** [comment]
> Operating system algorithms are missing
> Can i add one?

Sure @yukta12 . Just need to be implemented in Java. Create a new folder "Operating System" and add your algo in that folder.

**Comment by lunodesouza** [comment]
I've added JumpSearch Algorithm in Searching folder.

**Comment by cvaram96** [comment]
I have plan to add the Soundex algorithm

**Comment by cvaram96** [comment]
Guys, If you are working with this repository, Click the start button, and share with your friends

**Comment by cvaram96** [comment]
https://github.com/darpanjbora/Java-Algorithms/pull/87
I have sent the PR
