### ISSUE TITLE
Fix the README.md

### ISSUE THREAD

**Issue by darpanjbora** [darpanjbora/Java-Algorithms#27]
This repo is basically a one-stop for all the algorithms in Java. 

- [x] Kindly update the [README.md](https://github.com/darpanjbora/Java-Algorithms/blob/master/README.md) file with proper information of the repository.
- [x] Fix `all-contributors` (Refer [this](https://github.com/darpanjbora/Java-Algorithms/pull/21) to check the error) and update the contributors' list in [README.md](https://github.com/darpanjbora/Java-Algorithms/blob/master/README.md)

**Comment by Pika1998** [comment]
I would like to work on this

**Comment by darpanjbora** [comment]
> I would like to work on this

Thanks for contributing. :)
